### ISSUE TITLE
Question

### ISSUE THREAD

**Issue by Wolfhound905** [edde746/tiktok-downloader#1]
Is there any chance you could tell me what cookies are needed to make a request to the musicly api. Ones that get a non-watermarked video? My discord is Wolfhound905#1234

**Comment by edde746** [comment]
Hello, there are no cookies needed, the only cookies that are used are to prevent limiting on the API calls. The unwatermarked video is under the play_addr.url_list as seen [here](https://github.com/edde746/tiktok-downloader/blob/master/src/routes/video.js#L35)
